/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_uiautomation_iosdriver_services_LibImobileDeviceInstallerService */

#ifndef _Included_org_uiautomation_iosdriver_services_LibImobileDeviceInstallerService
#define _Included_org_uiautomation_iosdriver_services_LibImobileDeviceInstallerService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_uiautomation_iosdriver_services_LibImobileDeviceInstallerService
 * Method:    installNative
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_services_LibImobileDeviceInstallerService_installNative
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
