/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_uiautomation_iosdriver_services_LoggerService */

#ifndef _Included_org_uiautomation_iosdriver_services_LoggerService
#define _Included_org_uiautomation_iosdriver_services_LoggerService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_uiautomation_iosdriver_services_LoggerService
 * Method:    setLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_services_LoggerService_setLogLevel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
