/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_uiautomation_iosdriver_DeviceManager */

#ifndef _Included_org_uiautomation_iosdriver_DeviceManagerService
#define _Included_org_uiautomation_iosdriver_DeviceManagerService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_uiautomation_iosdriver_DeviceManager
 * Method:    getDeviceList
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_uiautomation_iosdriver_DeviceManagerService_getDeviceListNative
  (JNIEnv *, jobject);

/*
 * Class:     org_uiautomation_iosdriver_DeviceManager
 * Method:    getDeviceInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_uiautomation_iosdriver_DeviceManagerService_getDeviceInfoNative
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
