/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_uiautomation_iosdriver_services_DeviceInstallerService */

#ifndef _Included_org_uiautomation_iosdriver_services_DeviceInstallerService
#define _Included_org_uiautomation_iosdriver_services_DeviceInstallerService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_uiautomation_iosdriver_services_DeviceInstallerService
 * Method:    installNative
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_org_uiautomation_iosdriver_services_DeviceInstallerService_installNative
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_uiautomation_iosdriver_services_DeviceInstallerService
 * Method:    emptyApplicationCacheNative
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_services_DeviceInstallerService_emptyApplicationCacheNative  (JNIEnv *, jobject, jstring, jstring);





JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_services_DeviceInstallerService_setLockDownValue(JNIEnv *, jobject, jstring, jstring,jstring,jstring);

#ifdef __cplusplus
}
#endif
#endif
