/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_uiautomation_iosdriver_services_InstrumentsService */

#ifndef _Included_org_uiautomation_iosdriver_services_InstrumentsService
#define _Included_org_uiautomation_iosdriver_services_InstrumentsService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_uiautomation_iosdriver_services_InstrumentsService
 * Method:    executeScriptNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_services_InstrumentsService_executeScriptNative
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
