/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_uiautomation_iosdriver_WebInspector */

#ifndef _Included_org_uiautomation_iosdriver_services_WebInspectorService
#define _Included_org_uiautomation_iosdriver_services_WebInspectorService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_uiautomation_iosdriver_WebInspector
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_services_WebInspectorService_start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_uiautomation_iosdriver_WebInspector
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_services_WebInspectorService_stop
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_uiautomation_iosdriver_WebInspector
 * Method:    receiveMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_uiautomation_iosdriver_services_WebInspectorService_receiveMessage
  (JNIEnv *, jobject, jstring,jint);

/*
 * Class:     org_uiautomation_iosdriver_WebInspector
 * Method:    sendMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_services_WebInspectorService_sendMessage
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
