/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_uiautomation_iosdriver_DeviceInstallerService */

#ifndef _Included_org_uiautomation_iosdriver_DeviceInstallerService
#define _Included_org_uiautomation_iosdriver_DeviceInstallerService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_uiautomation_iosdriver_DeviceInstallerService
 * Method:    listAllApps
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_uiautomation_iosdriver_DeviceInstallerService_listAllApps
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_uiautomation_iosdriver_DeviceInstallerService
 * Method:    listUserApps
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_uiautomation_iosdriver_DeviceInstallerService_listUserApps
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_uiautomation_iosdriver_DeviceInstallerService
 * Method:    listSystemApps
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_uiautomation_iosdriver_DeviceInstallerService_listSystemApps
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_uiautomation_iosdriver_DeviceInstallerService
 * Method:    uninstall
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_DeviceInstallerService_uninstall
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_uiautomation_iosdriver_DeviceInstallerService
 * Method:    install
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_DeviceInstallerService_install
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_uiautomation_iosdriver_DeviceInstallerService
 * Method:    upgrade
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_DeviceInstallerService_upgrade
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_uiautomation_iosdriver_DeviceInstallerService
 * Method:    archive
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_DeviceInstallerService_archive
  (JNIEnv *, jobject, jstring, jstring, jboolean, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
