/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_uiautomation_iosdriver_WebInspector */

#ifndef _Included_org_uiautomation_iosdriver_WebInspector
#define _Included_org_uiautomation_iosdriver_WebInspector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_uiautomation_iosdriver_WebInspector
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_WebInspector_start
  (JNIEnv *, jobject);

/*
 * Class:     org_uiautomation_iosdriver_WebInspector
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_WebInspector_stop
  (JNIEnv *, jobject);

/*
 * Class:     org_uiautomation_iosdriver_WebInspector
 * Method:    receiveMessageImpl
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_uiautomation_iosdriver_WebInspector_receiveMessageImpl
  (JNIEnv *, jobject);

/*
 * Class:     org_uiautomation_iosdriver_WebInspector
 * Method:    sendMessageImpl
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_uiautomation_iosdriver_WebInspector_sendMessageImpl
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
